ReservAntes/ViewModels/DatosBancariosViewModel.cs
using ReservAntes.Extensions;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ReservAntes.ViewModels
{
    [MetadataType(typeof(DatosBancariosExtension))]
    public class DatosBancariosViewModel : DatosBancarios
    {
    }
}

ReservAntes/ViewModels/RestauranteViewModel.cs
using ReservAntes.Extensions;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ReservAntes.ViewModels
{
    [MetadataType(typeof(RestauranteExtension))]
    public class RestauranteViewModel : Restaurante
    {
    }
}

ReservAntes/Controllers/RestauranteController.cs
using ReservAntes.Models;
using ReservAntes.ViewModels;
using ReservAntes.ViewModels.Extensions;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ReservAntes.Extensions;
using mercadopago;
using System.Net.Mail;

namespace ReservAntes.Controllers
{
    //[Authorize]
    [HandleError]
    public class RestauranteController : Controller
    {

        dbReservantesEntities ctx = new dbReservantesEntities();
        LogicaRestaurante LogRes = new LogicaRestaurante();
        LogicaReserva LogRsv = new LogicaReserva();
        private LogicaDatosBancarios datosBancariosServicio = new LogicaDatosBancarios();
        private LogicaReserva reservaServicio = new LogicaReserva();
        // GET: Restaurante


        public ActionResult Index()

        {
            var IdUsuario = this.Session["usuarioId"];
            int numID = Convert.ToInt32(IdUsuario);

            List<Reserva> MisReservasResto = LogRsv.GetByUsuarioIdFechaActual(numID);

            //Disponibilidad ACTUAL de lugares libres
            ViewBag.OcupacionActual = this.AsientosReservadosDelRestaurante(DateTime.Now);
            ViewBag.CapacidadTotal = this.CapacidadTotalDelRestaurante();
            
            return View(MisReservasResto);
        }

        [HttpPost]
        public ActionResult CapacidadPorFecha()

        {
            //Lugares disponibles por busqueda
            String[] fechaArray = Request.Form["buscarPorFecha"].Split('-');
            Int32.TryParse(fechaArray.ElementAt(0), out int anio);
            Int32.TryParse(fechaArray.ElementAt(1), out int mes);
            Int32.TryParse(fechaArray.ElementAt(2), out int dia);

            String[] horaArray = Request.Form["buscarPorHora"].Split(':');
            Int32.TryParse(horaArray.ElementAt(0), out int hora);
            Int32.TryParse(horaArray.ElementAt(1), out int minuto);
            
            DateTime fechaHoraBuscada = new DateTime(anio, mes, dia, hora, minuto, 0);

            TempData["OcupacionPorFecha"] = this.AsientosReservadosDelRestaurante(fechaHoraBuscada);

            return RedirectToAction("Index");
        }

      

        // --------------------- PLATO -----------------------------

        //crear
        public ActionResult CreatePlato()
        {
            if (Session["usuarioId"] != null)
            {
                Int32.TryParse(Session["usuarioId"].ToString(), out int usuarioId);
                Restaurante restaurante = LogRes.GetByUserId(usuarioId);
                ViewBag.idResto = restaurante.IdRestaurante;
            }
            

            return View();
        }

        [HttpPost]
        public ActionResult CreatePlato(PlatoViewModel plato)
        {
            if (ModelState.IsValid)
            {
                bool resultado = this.LogRes.CrearPlato(plato);

                ViewBag.Guardado = resultado;
            }
            return View();
        }

        //listado de platos
        public ActionResult MiMenu()
        {
            List<Plato> platos = new List<Plato>();
            if (Session["usuarioId"] != null)
            {
                Int32.TryParse(Session["usuarioId"].ToString(), out int idUsuario);

                Restaurante restaurante = LogRes.GetByUserId(idUsuario);

                platos = LogRes.GetPlato(restaurante.IdRestaurante);
            }

            return View(platos);
        }

        //borrar platos
        [HttpGet]
        public ActionResult EliminarPlato(int idPlato)
        {
            bool resultado = LogRes.EliminarPlato(idPlato);

            if (resultado)
            {
                TempData["ResultadoEliminarPlato"] = "si";
            }


            return RedirectToAction("MiMenu");
        }


        //editar platos
        [HttpGet]
        public ActionResult EditarPlato(int idPlato)
        {
            Plato platoBuscado= ctx.Plato.Find(idPlato);

            PlatoViewModel plato = platoBuscado.Map();
            return View(plato);
        }

        
        [HttpPost]
        public ActionResult EditarPlato(PlatoViewModel plato)
        {
            if (ModelState.IsValid)
            {
                bool resultado = LogRes.EditarPlato(plato);

                if (resultado)
                {
                    ViewBag.Guardado = true;
                }
            }

            return View();
        }

        // --------------------------------------------------

        /* capacidad disponible del restaurante */
        public int AsientosReservadosDelRestaurante(DateTime fechaHora)
        {
            Int32.TryParse(Session["usuarioId"].ToString(), out int idUsuario);
            Restaurante restaurante = ctx.Restaurante.Where(x => x.IdUsuario == idUsuario).FirstOrDefault();
            
            return LogRes.VerCantidadDeComensales(restaurante.IdRestaurante, fechaHora);
        }

        /* capacidad total del restaurante */
        public int CapacidadTotalDelRestaurante()
        {
            Int32.TryParse(Session["usuarioId"].ToString(), out int idUsuario);
            Restaurante restaurante = ctx.Restaurante.Where(x => x.IdUsuario == idUsuario).FirstOrDefault();

            return restaurante.CantidadClientes.Value;
        }
       


        
        // --------------------- Perfil Restoran -------------------------------------------------------------------------------


        public ActionResult RestoPerfil()
        {
            var IdUsuario = Session["usuarioId"];
            var restauranteNuevo = new RestauranteViewModel();
            var restaurante = LogRes.GetByUserId(Convert.ToInt32(IdUsuario));
            if ( restaurante!= null)
            {
                restauranteNuevo = restaurante.Map();
            };
            return View(restauranteNuevo);
        }

        [HttpPost]
        public ActionResult RestoPerfil(RestauranteExtension restaurante)
        {
            
            var IdUsuario = Session["usuarioId"];
            if (restaurante == null)
            {
                throw new ArgumentNullException(nameof(restaurante));
            }

            if (restaurante.IdRestaurante == 0)
            {
                restaurante.Habilitado =false;
                restaurante.IdUsuario = Convert.ToInt32(Session["usuarioId"]);
            }

            
            var restauranteId = LogRes.GetByUserId(Convert.ToInt32(IdUsuario)).IdRestaurante;
            restaurante.IdRestaurante = restauranteId;

            this.LogRes.CreateOrUpdate(restaurante);
              

            
            return View();
        }

        //TRAER LAS IMAGENES 

        public FileContentResult getImgFoto(int id)
        {
            byte[] byteArrayFoto = ctx.Restaurante.Find(id).Foto;

            return byteArrayFoto != null
                ? new FileContentResult(byteArrayFoto, "image/jpeg/png")
                : null;


        }

        public FileContentResult getImgAFIP(int id)
        {
            byte[] byteArrayAFIP = ctx.Restaurante.Find(id).ConstAFIP;

            return byteArrayAFIP != null
                ? new FileContentResult(byteArrayAFIP, "image/jpeg/png")
                : null;
        }



        public ActionResult DatosBancarios()
        {
            var IdUsuario = Session["usuarioId"];
            var restaurante = LogRes.GetByUserId(Convert.ToInt32(IdUsuario));
            var datoBancario = new DatosBancariosViewModel();
            if (restaurante.DatosBancariosId != null)
            {
                var bancoResto = datosBancariosServicio.GetById(restaurante.DatosBancariosId.Value);
                datoBancario = bancoResto.Map();
            }
            return View("DatosBancarios", datoBancario);
        }

        [HttpPost]
        public ActionResult DatosBancarios(DatosBancariosViewModel datosBancarios)
        {
            var IdUsuario = Session["usuarioId"];
            var restaurante = LogRes.GetByUserId(Convert.ToInt32(IdUsuario));
            DatosBancarios datosBancariosDb = datosBancarios.Map();
            datosBancariosServicio.CreateOrupdate(datosBancariosDb);
            LogRes.ActualizaDatosBancarios(datosBancariosDb.Id, restaurante.IdRestaurante);
            //Todo: Agregar vista success
            return View();
        }




        [HttpGet]
        public ActionResult Reservas()
        {
            var IdUsuario = Session["usuarioId"];
            var restaurante = LogRes.GetByUserId(Convert.ToInt32(IdUsuario));
            var listado = new List<Reserva>();
            listado = reservaServicio.GetByRestauranteId(restaurante.IdRestaurante);
            if (listado == null || listado.Count() == 0)
                ModelState.AddModelError("SinReservas", "No se encontraron Reservas");
            return View("Reservas",listado);
        }


        public ActionResult OpcionesResto()
        {
            var IdUsuario = Session["usuarioId"];
            var restauranteNuevo = new RestauranteViewModel();
            var restaurante = LogRes.GetByUserId(Convert.ToInt32(IdUsuario));
            if (restaurante != null)
            {
                restauranteNuevo = restaurante.Map();
            };


            MP mp = new MP("3569046944289967", "VKUe2kZa2BemjDp7vgNHu3ZTLStjlIhh");

            return View(restauranteNuevo);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult OpcionesResto(RestauranteViewModel restoDeBaja)
        {

            var IdUsuario = Session["usuarioId"];
            var restauranteNuevo = new RestauranteViewModel();
            var restaurante = LogRes.GetByUserId(Convert.ToInt32(IdUsuario));

            

            ViewBag.Guardado = "Se le envio un mail al administrador para dar de baja el servicio." +
                        "Le pedimos por favor que aguarde que nosotros nos contactaremos con usted.";


            var message = new MailMessage();

ReservAntes/Views/Restaurante/CreatePlato.cshtml
@model ReservAntes.ViewModels.PlatoViewModel
@{
    ViewBag.Title = "CreatePlato";
    Layout = "~/Views/Shared/_LayoutRestaurante.cshtml";

    int idResto = 0;

    if (ViewBag.idResto != null)
    {
        idResto = ViewBag.idResto;
    }
}



<div class="jumbotron">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            @{
                if (ViewBag.Guardado != null && ViewBag.Guardado == true)
                {
                    <div class="alert alert-success">
                        Plato creado correctamente
                    </div>
                }
            }
        </div>
    </div>
        <div class="row">
            @using (Html.BeginForm("CreatePlato", "Restaurante", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.ValidationSummary(true)
                <div class="form-group col-md-4 col-md-offset-4">
                    @Html.Hidden("RestauranteId", idResto)
                    <div class="form-group">
                        <label>Nombre del Plato:</label>
                        @Html.TextBoxFor(p => p.NombrePlato, new { @class = "form-control" })
                        @Html.ValidationMessageFor(p => p.NombrePlato, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label>Descripcion:</label>
                        @Html.TextAreaFor(p => p.Descripcion, new { @class = "form-control" })
                        @Html.ValidationMessageFor(p => p.Descripcion, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <label>Precio:</label>
                        @Html.TextBoxFor(p => p.Precio, new { @class = "form-control" })
                        @Html.ValidationMessageFor(p => p.Precio, "", new { @class = "text-danger" })
                    </div>
                    @*     <div class="form-group">
                        <label>Foto:</label>
                        @Html.TextBoxFor(Model => Model.Foto, new { type = "file" })

                    </div>*@
                    <div><input type="submit" value="Crear Plato" class="btn btn-info" /></div>
                </div>

            }
        </div>
</div>

ReservAntes/Views/Restaurante/DatosBancarios.cshtml
@model ReservAntes.DatosBancarios
@{
    ViewBag.Title = "DatosBancarios";
    Layout = "~/Views/Shared/_LayoutRestaurante.cshtml";
}



<div class="jumbotron">
    <h2>Datos Bancarios</h2>
    <hr />
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-6">

            @using (Html.BeginForm("DatosBancarios", "Restaurante"))
            {
                @Html.HiddenFor(u => u.Id)
                <div class="form-group">
                    <label>Numero de Cuenta:</label>
                    @Html.TextBoxFor(Model => Model.NumeroCuenta, new { @class = "form-control" })
                    @Html.ValidationMessageFor(Model => Model.NumeroCuenta, "", new { @class = "text-danger" })


                </div>
                <div class="form-group">
                    <label>CBU:</label>
                    @Html.TextBoxFor(Model => Model.CBU, new { @class = "form-control" })
                    @Html.ValidationMessageFor(Model => Model.CBU, "", new { @class = "text-danger" })

                </div>

                <button type="submit" class="btn btn-primary">Cargar</button>
                <button onclick="location.href='@Url.Action("Index", "Restaurante")';return false;" class="btn btn-danger">Cancelar</button>
            }
        </div>
    </div>
</div>

ReservAntes/Views/Restaurante/Domicilio.cshtml
@using ReservAntes.ViewModels
@model  DomicilioViewModel
@{
    Layout = "~/Views/Shared/_LayoutRestaurante.cshtml";
}

<h2>Perfil del Restaurante</h2>
<div class="jumbotron">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-6">
            @using (Html.BeginForm("Domicilio", "Restaurante"))
            {
                <div>
                    @Html.HiddenFor(u => u.Id)


                    <h3>Ingrese datos de domicilio</h3>
                    <div class="form-group">
                        <label>Calle:</label>
                        @Html.TextBoxFor(Model => Model.NombreCalle, new { @class = "form-control" })
                        @Html.ValidationMessageFor(u => u.NombreCalle)
                    </div>
                    <div class="form-group">
                        <label>Número:</label>
                        @Html.TextBoxFor(Model => Model.NumeroCalle, new { @class = "form-control" })
                        @Html.ValidationMessageFor(u => u.NumeroCalle)

                    </div>
                    <div class="form-group">
                        <label>Piso:</label>
                        @Html.TextBoxFor(Model => Model.NumeroPiso, new { @class = "form-control" })
                        @Html.ValidationMessageFor(u => u.NumeroPiso)

                    </div>
                    <div class="form-group">
                        <label>Departamento:</label>
                        @Html.TextBoxFor(Model => Model.NumeroDpto, new { @class = "form-control" })
                        @Html.ValidationMessageFor(u => u.NumeroDpto)


                    </div>

                    <div class="form-group">
                        <!--Localidades-->
                        @Html.LabelFor(u => u.Localidad.Id, "Localidades", new { @class = "col-lg-2 control-label" })
                        @Html.DropDownListFor(u => u.LocalidadId, new SelectList(Model.localidades, "Id", "Descripcion"), "Seleccione", new { @class = "form-control" })
                        @Html.ValidationMessageFor(u => u.LocalidadId)

                    </div>
                    <button type="submit" class="btn btn-primary">Ingresar</button>
                    <button onclick="location.href='@Url.Action("DatosBancarios", "Restaurante")';return false;" class="btn btn-danger">Siguiente</button>

                </div>
            }

        </div>
    </div>
</div>

ReservAntes/Views/Restaurante/EditarPlato.cshtml
@model ReservAntes.ViewModels.PlatoViewModel
@{
    ViewBag.Title = "EditarPlato";
    Layout = "~/Views/Shared/_LayoutRestaurante.cshtml";
}

<h2>EditarPlato</h2>

<div class="jumbotron">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            @{
                if (ViewBag.Guardado != null && ViewBag.Guardado == true)
                {
                    <div class="alert alert-success">
                        Plato editado correctamente
                    </div>
                }
            }
        </div>
    </div>
    <div class="row">
        @using (Html.BeginForm("EditarPlato", "Restaurante", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
            @Html.ValidationSummary(true)
            <div class="form-group col-md-4 col-md-offset-4">
                @Html.HiddenFor(p => p.Id)
                <div class="form-group">
                    <label>Nombre del Plato:</label>
                    @Html.TextBoxFor(p => p.NombrePlato, new { @class = "form-control" })
                    @Html.ValidationMessageFor(p => p.NombrePlato, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label>Descripcion:</label>
                    @Html.TextAreaFor(p => p.Descripcion, new { @class = "form-control" })
                    @Html.ValidationMessageFor(p => p.Descripcion, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <label>Precio:</label>
                    @Html.TextBoxFor(p => p.Precio, new { @class = "form-control" })
                    @Html.ValidationMessageFor(p => p.Precio, "", new { @class = "text-danger" })
                </div>
                @*     <div class="form-group">
                        <label>Foto:</label>
                        @Html.TextBoxFor(Model => Model.Foto, new { type = "file" })

                    </div>*@
                <div><input type="submit" value="Guardar cambios" class="btn btn-info" /></div>
            </div>

        }
    </div>
</div>

ReservAntes/Views/Restaurante/Index.cshtml
@model List<Reserva>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutRestaurante.cshtml";
}

<!-- declaracion y seteo de variables -->
@{
    /* actual */
    int asientosLibres = 0;
    if (ViewBag.CapacidadTotal != null && ViewBag.OcupacionActual != null)
    {
        asientosLibres = ViewBag.CapacidadTotal - ViewBag.OcupacionActual;
    }


    /* busqueda */
    int ocupacionPorFecha;

    if (TempData["OcupacionPorFecha"] == null)
    {
        ocupacionPorFecha = 0;
    }
    else
    {
        Int32.TryParse(TempData["OcupacionPorFecha"].ToString(), out ocupacionPorFecha);
    }

    int asientosLibresPorFecha = 0;
    if (ViewBag.CapacidadTotal != null)
    {
        asientosLibresPorFecha = ViewBag.CapacidadTotal - ocupacionPorFecha;
    }


}
                    
<br />
<div class="thumbnail"><h4> Reservas de Hoy -- @DateTime.Now.Day/@DateTime.Now.Month/@DateTime.Now.Year</h4></div>
<br />

<div class="thumbnail">
    <h3>Capacidad disponible ahora:</h3>
   
    <!-- grafico actual -->
    <p>@asientosLibres lugares libres de @ViewBag.CapacidadTotal disponibles</p>
        <div class="row">
            <div class="col-xs-12 col-md-6">
                @for (int i = 1; i <= asientosLibres; i++)
                {
                    <div class="sillaLibre col-xs-1">

                    </div>
                }

                @for (int i = 1; i <= @ViewBag.OcupacionActual; i++ )
                {
                    <div class="sillaOcupada col-xs-1">
                        
                    </div>
                }
            </div>
        </div>
    </div>

<!-- disponibilidad por fecha y hora -->
<div class="thumbnail">
    <h3>Capacidad disponible por fecha y hora:</h3>
    
    <!-- formulario del buscador -->
    @using (Html.BeginForm("CapacidadPorFecha", "Restaurante", FormMethod.Post))
    {
        <input type="date" name="buscarPorFecha" />
        <input type="time" name="buscarPorHora" />

        <input type="submit" value="Ver" />
    }

    <!-- grafico de busqueda -->
    <p>@asientosLibresPorFecha lugares libres de @ViewBag.CapacidadTotal disponibles</p>

    <div class="row">
        <div class="col-xs-12 col-md-6">
            @for (int i = 1; i <= asientosLibresPorFecha; i++)
            {
                <div class="sillaLibre col-xs-1">

                </div>
            }

            @for (int i = 1; i <= ocupacionPorFecha; i++)
            {
                <div class="sillaOcupada col-xs-1">

                </div>
            }
        </div>
    </div>
</div>


<div>
    <div class="thumbnail">
        <table class="table table-bordered table-responsive table-striped">
            <thead>
                <tr>
                    <th>Codigo de Reserva</th>
                    <th>Usuario</th>
                    <th>Observaciones</th>
                </tr>
            </thead>
            <tbody>
                @if(Model != null) {
                    foreach (Reserva item in Model)
                    {
                        <tr>
                            <th>@item.CodigoReserva</th>
                            <th>@item.ClienteId</th>
                            <th>@item.Observaciones</th>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>

</div>

ReservAntes/Views/Restaurante/MiMenu.cshtml
@model List<Plato>
@{
    ViewBag.Title = "MisMenues";
    Layout = "~/Views/Shared/_LayoutRestaurante.cshtml";
}

<div class="container thumbnail">
    <h2>Mi Menu</h2>
    <hr />
    <div class="container">
        <div class="row">
            <div class="col-md-9"></div>
            <button class="col-md-2 btn btn-primary" onclick="location.href='@Url.Action("CreatePlato")'; return false;"><span class="glyphicon glyphicon-plus-sign"></span>  Crear Nuevo Plato</button>
        </div><br />

        <div class="row">
            <div class="col-md-10 col-md-offset-1 text-center">
                @{
                    if (TempData["ResultadoEliminarPlato"] != null && TempData["ResultadoEliminarPlato"].ToString() == "si")
                    {
                        <div class="alert alert-success">
                            Plato eliminado
                        </div>
                    }
                }
            </div>
        </div>

        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr class="info">
                                <!-- <th>Imagen</th> -->
                                <th>Nombre</th>
                                <th>Descripcion</th>
                                <th>Precio</th>
                                <th>Editar</th>
                                <th>Eliminar</th>
                            </tr>
                        </thead>
                        <tbody class="table table-hover">
                            @foreach (Plato plat in Model)
                            {
                                <tr>
                                    <!-- <th><img src="@plat.Foto" width="70" /></th> -->
                                    <th>@plat.NombrePlato</th>
                                    <th>@plat.Descripcion</th>
                                    <th>$@plat.Precio</th>
                                    <th class="text-center"><a href="@Url.Action("EditarPlato", "Restaurante", new { idPlato = plat.Id})" class="btn btn-default"><span class="glyphicon glyphicon-pencil"></span></a></th>
                                    <th class="text-center"><a href="@Url.Action("EliminarPlato", "Restaurante", new { idPlato = plat.Id})" class="btn btn-danger"><span class="glyphicon glyphicon-remove"></span></a></th>

                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

ReservAntes/Views/Restaurante/RestoPerfil.cshtml
@using ReservAntes.ViewModels

@model  RestauranteViewModel
@{
    ViewBag.Title = "RestoPerfil";
    Layout = "~/Views/Shared/_LayoutRestaurante.cshtml";
}
<div class="jumbotron">

    <h4> Para poder completar el registro debe llenar los siguientes campos:</h4>

    <hr />

    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-11">

            @using (Html.BeginForm("RestoPerfil", "Restaurante", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @*@Html.HttpMethodOverride(HttpVerbs.Put)*@
        @Html.AntiForgeryToken()
        @Html.HiddenFor(Model => Model.IdRestaurante);


        <div class="form-group">
            <label><b>Nombre Comercial:</b></label>
            @Html.TextBoxFor(Model => Model.NombreComercial, new { @class = "form-control" })
            @Html.ValidationMessageFor(p => p.NombreComercial, "", new { @class = "text-danger" })


        </div>
        <div class="form-group">
            <label><b>CUIT:</b></label>
            @Html.TextBoxFor(Model => Model.CUIT, new { @class = "form-control" })
            @Html.ValidationMessageFor(p => p.CUIT, "", new { @class = "text-danger" })

        </div>

        <div class="form-group">
            <label><b>Cantidad máxima de clientes:</b></label>
            @Html.TextBoxFor(Model => Model.CantidadClientes, new { @class = "form-control" })
            @Html.ValidationMessageFor(p => p.CantidadClientes, "", new { @class = "text-danger" })
            <p></p>

        </div>
        <div class="form-group">
            <label><b>Foto:</b></label>
            @Html.TextBoxFor(Model => Model.Foto, new { type = "file" })
            @Html.ValidationMessageFor(p => p.Foto, "", new { @class = "text-danger" })
            <p></p>
        </div>
        <div class="form-group">
            <label><b>Constancia de inscripcion a la AFIP: <em>(*)</em></b></label>
            @Html.TextBoxFor(Model => Model.ConstAFIP, new { type = "file" })
            @Html.ValidationMessageFor(p => p.ConstAFIP, "", new { @class = "text-danger" })<p></p>
            <em class="small">(*)Les pedimos por favor que cargue un archivo de tipo .pdf, </em><br />
            <em class="small">el mismo podra descargarlo desde el siguiente enlace <a href="https://seti.afip.gob.ar/padron-puc-constancia-internet/ConsultaConstanciaAction.do">Constancia AFIP.</a> </em>


        </div>

        <style>
            #map-canvas {
                width: 300px;
                height: 350px;
                background-color: grey;
                border: solid 1px;
            }
        </style>

        <div style="width:320px; margin:-410px 0 0 500px;">
            <label><b>Direccion:</b></label>
            @Html.TextBoxFor(Model => Model.Domicilio, new { @class = "form-control", id = "direccion" })
            <p></p>
            <span id="geocoding"></span>
            <div id="map-canvas"></div>

        </div>
        <div style="visibility:hidden">
            <label><b>Coordenadas:</b></label>
            <input type="text" id="coordenadas" />

            @Html.TextBoxFor(Model => Model.Latitud, new { @class = "form-control", id = "Latitud" })

            @Html.TextBoxFor(Model => Model.Longitud, new { @class = "form-control", id = "Longitud" })
        </div>

        <p></p>

        <button type="submit" class="btn btn-primary">Ingresar</button>
        <hr style="color:#000000" ; />
}


            <button onclick="location.href='@Url.Action("DatosBancarios", "Restaurante")';return false;" class="btn btn-success pull-right">Cargar Datos Bancarios</button>
            @Html.ValidationSummary(true, "");

        </div>
    </div>
</div>


<script>
    var map;
    var geocoder;
    var infoWindow;
    var marker;

    function iniciarNuevo() {

        var mapOptions = {
            center: new google.maps.LatLng(-34.611170889697334, -58.40778350830078),
            zoom: 11,
            mapTypeId: google.maps.MapTypeId.G_NORMAL_MAP
        };
        var map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
        geocoder = new google.maps.Geocoder();
        infowindow = new google.maps.InfoWindow();

        google.maps.event.addListener(map, 'click', function (event) {
            geocoder.geocode(
                { 'latLng': event.latLng },
                function (results, status) {
                    if (status == google.maps.GeocoderStatus.OK) {
                        if (results[0]) {

                            document.getElementById('direccion').value = results[0].formatted_address;
                            var coord = document.getElementById('coordenadas');
                            coord.value = results[0].geometry.location;    

                            coord.value = coord.value.replace("(", "").replace(")", "");
                           
                            var arrD = coord.value.split(',');
                            document.getElementById('Latitud').value = arrD[0].replace(".",",");
                            document.getElementById('Longitud').value = arrD[1].replace(".", ",");
                            
                            if (marker) {
                                marker.setPosition(event.latLng);
                            } else {
                                marker = new google.maps.Marker({
                                    position: event.latLng,
                                    map: map
                                });
                            }



                            infowindow.setContent(results[0].formatted_address + '<br/> Coordenadas: ' + results[0].geometry.location);
                            infowindow.open(map, marker);
                                

                        } else {
                            document.getElementById('geocoding').innerHTML =
                                'No se encontraron resultados';
                        }
                    } else {
                        document.getElementById('geocoding').innerHTML =
                            'Geocodificación  ha fallado debido a: ' + status;
                    }
                });
        });

    }




</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAptrGun-vHjygAsSermQUGiDvxOGQ_qJ8&libraries=places&callback=iniciarNuevo" async defer></script>