ReservAntes/Controllers/ReservaController.cs
using ReservAntes.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ReservAntes.Controllers
{
    public class ReservaController : Controller
    {

        dbReservantesEntities ctx = new dbReservantesEntities();

        ReservAntes.Models.LogicaReserva LogRes = new LogicaReserva();

        // GET: Reserva
        public ActionResult ReporteReservas()
        {
            var IdUsuario = this.Session["usuarioId"];
            int numID = Convert.ToInt32(IdUsuario);

            List<Reserva> MisReservasResto = LogRes.GetByUsuarioId(numID);

            return View(MisReservasResto);
        }

        [HttpPost]
        public ActionResult ReporteReservas(FormCollection form)
        {
            var IdUsuario = this.Session["usuarioId"];
            int numID = Convert.ToInt32(IdUsuario);

            //var fechaFil = form["FFiltro"];
            //Convert.ToDateTime(fechaFil);
            DateTime fechaFil = Convert.ToDateTime(form["FFiltro"]);

            List<Reserva> reservaFiltro = LogRes.FiltroReservas(numID, fechaFil);

            
            return View(reservaFiltro);
        }


  
        public ActionResult ReservaHorarios()
        {
            return View();
        }


        // GET: Reserva/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Reserva/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Reserva/Edit/5
        public ActionResult CancelarReserva(int id)
        {
            return View();
        }

        // POST: Reserva/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Reserva/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Reserva/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ReservAntes/Controllers/UsuarioController.cs
using ReservAntes.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ReservAntes.Extensions;
using System.Net.Mail;
using System.Security.Cryptography;


namespace ReservAntes.Controllers
{
    public class UsuarioController : Controller
    {
        dbReservantesEntities ctx = new dbReservantesEntities();

        LogicaUsuario LogUs = new LogicaUsuario();



        // GET: Usuario
        public ActionResult Index()
        {
            return View();
        }

     

        // GET: Usuario/Create
        public ActionResult CreateUser()
        {
            if (Session["usuarioTipo"] != null)
            {
                if (Session["usuarioTipo"].ToString() != "1")
                {
                    Response.Redirect("../home/Index");
                }
                
            }

            ViewBag.ListUsuario = LogUs.GetTiposDeUs();
            return View();
        }

    
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateUser(UsuarioExtension user)
        {
        
            
                if (ModelState.IsValid)
                {
                    var emailEx = ctx.Usuario.Any(a => a.Email == user.Email);
                    
                    if (emailEx == true)
                    {
                       ViewBag.Error = "Ya hay un email registrado";
                       ViewBag.ListUsuario = LogUs.GetTiposDeUs();
                       return View();

                    }

                ViewBag.ListUsuario = LogUs.GetTiposDeUs();
                        this.LogUs.CrearUsuario(user);
                        ViewBag.Guardado = "Felicidades. Usted se ha registrado con exito." +
                            "Verifique por favor que ha recibido el mail de confirmacion.";

                        var message = new MailMessage();
                        message.From = new MailAddress("reservantesapp@gmail.com");
                        message.To.Add(user.Email);
                        message.Subject = "Registro ReservAntes";
                        message.Body = "<div class='container'>" +
                            " <h4>Felicidades " + user.Username  + " usted se ha registrado con Exito en ReservAntes </h4> " +
                            "En caso de cualquier detalle tecnico le pedimos por favor que se comunique con reservantesapp@gmail.com " +
                            "La contraseña que usted ha ingresado es: " + user.Password +
                            "</div>";
                        message.IsBodyHtml = true;
                        message.Priority = MailPriority.Normal;


                    SmtpClient smtp = new SmtpClient();
                    smtp.Host = "smtp.gmail.com";
                    smtp.Port = 25;
                    smtp.EnableSsl = true;
                    string sCorreoReservAntes = "reservantesapp@gmail.com";
                    string sPsswordReservantes = "ReservAntes007";
                    smtp.Credentials = new System.Net.NetworkCredential(sCorreoReservAntes, sPsswordReservantes);
                    smtp.Send(message);


            } 
                

                ViewBag.ListUsuario = LogUs.GetTiposDeUs();
                return View();
                
            

        }

       

        // GET: Usuario/Delete/5
        public ActionResult Delete(int id)
        {
            this.LogUs.EliminarUs(id);

            return RedirectToAction("../Admin/VerUsuarios");
        }



    
    }
}

ReservAntes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script src="~/Scripts/GoogleMaps.js" type="text/javascript"></script>

    <link rel="icon" type="image/png" href="~/Imagenes/icono.png" />
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Oxygen" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
</head>
<body>

        @RenderBody()
                    
                    <footer>
                        <div class="container"><br />
                            <div class="col-xs-12">
                                <h7 style="color:gray; font-size:small;">Al continuar a la siguiente página, usted está de acuerdo con nuestra Términos de Servicio, Política de Cookie, Política de Privacidad y Políticas de Contenido. Todas las marcas son propiedad de sus respectivos dueños. © 2017 - ReservAntes™</h7>

                            </div>
                            <hr />

                        </div>
                    </footer>
               
                @Scripts.Render("~/bundles/jquery")
                @Scripts.Render("~/bundles/bootstrap")
                @RenderSection("scripts", required: false)

    
</body>
</html>

ReservAntes/Views/Shared/_LayoutAdmin.cshtml
@{
    ViewBag.Title = "Admin";
    Layout = "~/Views/Shared/_Layout.cshtml";

    //redireccion por permisos
    if (Session["usuarioTipo"] == null || Session["usuarioTipo"].ToString() != "1")
    {
        Response.Redirect("/ReservAntes/Home/Index/");
    }

    <!-- menu principal -->
    if (Session["usuarioTipo"] == null)
    {
        @Html.Partial("~/Views/Shared/_NavegacionVisitante.cshtml")
    }
    else if (Session["usuarioTipo"].ToString() == "1")
    {
        @Html.Partial("~/Views/Shared/_NavegacionAdmin.cshtml")
    }
    else if (Session["usuarioTipo"].ToString() == "2")
    {
        @Html.Partial("~/Views/Shared/_NavegacionCliente.cshtml")
    }
    else if (Session["usuarioTipo"].ToString() == "3")
    {
        @Html.Partial("~/Views/Shared/_NavegacionRestaurante.cshtml")
    }
}
<br />

<div class="container alturaMinimaDeSecciones">
    @RenderBody()
</div>

ReservAntes/Views/Shared/_LayoutCliente.cshtml
@{
    ViewBag.Title = "Cliente";
    Layout = "~/Views/Shared/_Layout.cshtml";

    //redireccion por permisos
    var nombreDeVista = Request.Url.Segments[3];

    if (nombreDeVista != "ListaPlatos/")
    {
        if (Session["usuarioTipo"] == null || Session["usuarioTipo"].ToString() != "2")
        {
            Response.Redirect("/ReservAntes/Home/Index/");
        }
    }


    <!-- menu principal -->
    if (Session["usuarioTipo"] == null)
    {
        @Html.Partial("~/Views/Shared/_NavegacionVisitante.cshtml")
    }
    else if (Session["usuarioTipo"].ToString() == "1")
    {
        @Html.Partial("~/Views/Shared/_NavegacionAdmin.cshtml")
    }
    else if (Session["usuarioTipo"].ToString() == "2")
    {
        @Html.Partial("~/Views/Shared/_NavegacionCliente.cshtml")
    }
    else if (Session["usuarioTipo"].ToString() == "3")
    {
        @Html.Partial("~/Views/Shared/_NavegacionRestaurante.cshtml")
    }
}

    <br />


<div class="container alturaMinimaDeSecciones">
    @RenderBody()
</div>

ReservAntes/Views/Shared/_LayoutHome.cshtml
@{
    ViewBag.Title = "ReservAntes";
    Layout = "~/Views/Shared/_Layout.cshtml";

    <!-- menu principal -->
    if (Session["usuarioTipo"] == null)
    {
        @Html.Partial("~/Views/Shared/_NavegacionVisitante.cshtml")
    }
    else if (Session["usuarioTipo"].ToString() == "1")
    {
        @Html.Partial("~/Views/Shared/_NavegacionAdmin.cshtml")
    }
    else if (Session["usuarioTipo"].ToString() == "2")
    {
        @Html.Partial("~/Views/Shared/_NavegacionCliente.cshtml")
    }
    else if (Session["usuarioTipo"].ToString() == "3")
    {
        @Html.Partial("~/Views/Shared/_NavegacionRestaurante.cshtml")
    }
}



<div class="container alturaMinimaDeSecciones">
    <br />
    @RenderBody()
</div>

@RenderSection("scripts", false)

ReservAntes/Views/Shared/_LayoutRestaurante.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    //redireccion por permisos
    if (Session["usuarioTipo"] == null || Session["usuarioTipo"].ToString() != "3")
    {
        Response.Redirect("/ReservAntes/Home/Index/");
    }

    <!-- menu principal -->
    if (Session["usuarioTipo"] == null)
    {
        @Html.Partial("~/Views/Shared/_NavegacionVisitante.cshtml")
    }
    else if (Session["usuarioTipo"].ToString() == "1")
    {
        @Html.Partial("~/Views/Shared/_NavegacionAdmin.cshtml")
    }
    else if (Session["usuarioTipo"].ToString() == "2")
    {
        @Html.Partial("~/Views/Shared/_NavegacionCliente.cshtml")
    }
    else if (Session["usuarioTipo"].ToString() == "3")
    {
        @Html.Partial("~/Views/Shared/_NavegacionRestaurante.cshtml")
    }
}

    <br />
<br />

<div class="container alturaMinimaDeSecciones">
    @RenderBody()
</div>

@RenderSection("scripts", false)

ReservAntes/Views/Shared/_NavegacionAdmin.cshtml
<nav class="navbar navbar-default" id="menuPrincipal">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mibarrita">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a href='@Url.Action("Index", "Home")'>
                <img src="~/Imagenes/Logo.png" alt="Reservantes" class="img-responsive" />
            </a>

        </div>
        <div class="collapse navbar-collapse" id="mibarrita">
            <ul class="nav navbar-nav hidden-xs hidden-sm hidden-md">
                <li class="slogan">
                    <em>No esperes la comida, la comida te espera a vos</em>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li><a>@Session["usuarioNombre"]</a></li>
                <li>@Html.ActionLink("Salir", "Logout", "Login")</li>
            </ul>
        </div>
    </div>
</nav>

<!-- menu de admin -->
<nav class="navbar navbar-default" id="menuPrincipal">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#barraAdministracion">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <label class="hidden-lg hidden-md hidden-sm">Administración</label>

        </div>
        <div class="collapse navbar-collapse" id="barraAdministracion">
            <ul class="nav navbar-nav">
                <li>
                    <button onclick="location.href='@Url.Action("Index","Admin")'; return false;" class="btn btn-rojo">Inicio admin</button>
                </li>
                <li>
                    <button onclick="location.href='@Url.Action("VerRestaurantes","Admin")'; return false;" class="btn btn-rojo">Ver Restaurantes</button>
                </li>
                <li>
                    <button onclick="location.href='@Url.Action("VerClientes","Admin")'; return false;" class="btn btn-rojo">Ver Clientes</button>
                </li>
                <li>
                    <button onclick="location.href='@Url.Action("VerUsuarios","Admin")'; return false;" class="btn btn-rojo">Ver Usuarios</button>
                </li>
            </ul>
        </div>
    </div>
</nav>

ReservAntes/Views/Shared/_NavegacionCliente.cshtml
<!-- menu principal -->
<nav class="navbar navbar-default" id="menuPrincipal">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mibarrita">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href='@Url.Action("Index", "Home")'>
                <img src="~/Imagenes/Logo.png" alt="Reservantes" class="img-responsive" />
            </a>
        </div>
        <div class="collapse navbar-collapse" id="mibarrita">
            <ul class="nav navbar-nav hidden-xs hidden-sm hidden-md">
                <li class="slogan">
                    <em>No esperes la comida, la comida te espera a vos</em>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                <li><a>@Session["usuarioNombre"]</a></li>
                <li>@Html.ActionLink("Salir", "Logout", "Login")</li>
            </ul>
        </div>
    </div>
</nav>
<!-- menu de cliente -->
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#barraAdministracion">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <label class="hidden-lg hidden-md hidden-sm">Administración</label>
        </div>
        <div class="collapse navbar-collapse" id="barraAdministracion">
            <ul class="nav navbar-nav">
                <li>
                    <button onclick="location.href='@Url.Action("DetalleCliente","Cliente", new { id = Convert.ToInt32(Session["usuarioId"].ToString())})'; return false;" class="btn btn-gris"><span class="glyphicon glyphicon-user"></span>  Mi Perfil</button>
                </li>
                <li>
                    <button onclick="location.href='@Url.Action("ReservaCliente","Cliente")'; return false;" class="btn btn-gris"><span class="glyphicon glyphicon-th-list"></span>  Mis Reservas</button>
                </li>
            </ul>
        </div>
    </div>
</nav>

ReservAntes/Views/Shared/_NavegacionRestaurante.cshtml
<!-- menu principal -->
<nav class="navbar navbar-default" id="menuPrincipal" style="z-index:0;">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mibarrita">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a href='@Url.Action("Index", "Home")'>
                <img src="~/Imagenes/Logo.png" alt="Reservantes" class="img-responsive" />
            </a>

        </div>

        <div class="collapse navbar-collapse" id="mibarrita" >
            <ul class="nav navbar-nav hidden-xs hidden-sm hidden-md">
                <li class="slogan">
                    <em>No esperes la comida, la comida te espera a vos</em>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right" >
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                <li><a>@Session["usuarioNombre"]</a></li>
                <li>@Html.ActionLink("Salir", "Logout", "Login")</li>
            </ul>
        </div>
    </div>
</nav>
<!-- menu de Restaurante -->
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#barraAdministracion">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <label class="hidden-lg hidden-md hidden-sm">Administración</label>

        </div>
        <div class="collapse navbar-collapse" id="barraAdministracion">
            <ul class="nav navbar-nav">
                <li>
                    <button onclick="location.href='@Url.Action("Index","Restaurante")'; return false;" class="btn btn-warning"><span class="glyphicon glyphicon-home"></span>  Mi Restaurante</button>
                </li>
                <li>
                    <button onclick="location.href='@Url.Action("RestoPerfil","Restaurante")'; return false;" class="btn btn-warning"><span class="glyphicon glyphicon-user"></span> Mi Perfil</button>
                </li>
                @*<li>
                    <button onclick="location.href='@Url.Action("ReporteReservas","Reserva")'; return false;" class="btn btn-warning">Reservas</button>
                </li>*@
                <li>
                    <button onclick="location.href='@Url.Action("MiMenu","Restaurante")'; return false;" class="btn btn-warning"><span class="glyphicon glyphicon-list-alt"></span>  Ver Menú</button>
                </li>
                <li>
                    <button onclick="location.href='@Url.Action("OpcionesResto","Restaurante")'; return false;" class="btn btn-warning"><span class="glyphicon glyphicon-wrench"></span>  Opciones</button>
</li>
            </ul>
        </div>
    </div>
</nav>

ReservAntes/Views/Shared/_NavegacionVisitante.cshtml
<nav class="navbar navbar-default" id="menuPrincipal">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mibarrita">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a href='@Url.Action("Index", "Home")'>
                <img src="~/Imagenes/Logo.png" alt="Reservantes" class="img-responsive" />
            </a>
        </div>

        <div class="collapse navbar-collapse" id="mibarrita">
            <ul class="nav navbar-nav hidden-xs hidden-sm hidden-md">
                <li class="slogan">
                    <em>No esperes la comida, la comida te espera a vos</em>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                <li>@Html.ActionLink("Registrarse", "CreateUser", "Usuario")</li>
                <li>@Html.ActionLink("Login", "Login", "Login")</li>
            </ul>
        </div>
    </div>
</nav>