ReservAntes/ViewModels/ClienteViewModel.cs
using ReservAntes.Extensions;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ReservAntes.ViewModels
{
    [MetadataType(typeof(ClienteExtension))]
    public class ClienteViewModel : Cliente
    {
    }
}

ReservAntes/ViewModels/ReservaViewModel.cs
using ReservAntes.Extensions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ReservAntes.ViewModels
{
    [MetadataType(typeof(ReservaExtension))]
    public class ReservaViewModel : Reserva
    {
        //public List<EstadoReserva> estados { get; set; }
        public List<int> cantidadMaxima { get; set; }
        public string restauranteNombre { get; set; }
        public List<PlatoViewModel> platos { get; set; }
        //public RestauranteViewModel restauranteElegido { get; set; }
        public List<int> PlatoCantidad { get; set; }
        public List<int> PlatoId { get; set; }
        public List<int> PlatoElegidoCantidad { get; set; }
        public List<int> PlatoElegidoId { get; set; }
        public List<PlatosElegidosViewModel> platosElegidosVm { get; set; }

    }
}

ReservAntes/Controllers/ClienteController.cs
using mercadopago;
using ReservAntes;
using ReservAntes.Extensions.Enums;
using ReservAntes.Models;
using ReservAntes.ViewModels;
using ReservAntes.ViewModels.Extensions;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.UI;
using System.Net.Mail;


namespace ReservAntes.Controllers
{
    //[Authorize]
    [HandleError]
    public class ClienteController : Controller
    {

        dbReservantesEntities ctx = new dbReservantesEntities();

        LogicaCliente LogCliente = new LogicaCliente();
        LogicaRestaurante restauranteServicio = new LogicaRestaurante();
        LogicaPlato logicaPlato = new LogicaPlato();
        LogicaReserva logicaReserva = new LogicaReserva();
        // GET: Cliente
        public ActionResult Index()
        {
            List<RestauranteViewModel> listadoRestaurante = new List<RestauranteViewModel>();

            return View(listadoRestaurante);
        }


        // POST: Cliente/Edit/5
        [HttpPost]
        public ActionResult EditCliente(int id, Cliente editCl)
        {

            var IdUsuario = Session["usuarioId"];
            var nomUsuario = Session["usuarioNombre"];


            if (ModelState.IsValid)
            {


                Cliente EditCliente = new Cliente();

                EditCliente.IdUsuario = Convert.ToInt32(IdUsuario);
                EditCliente.Nombre = editCl.Nombre;
                EditCliente.Apellido = editCl.Apellido;

                ctx.Cliente.Add(EditCliente);
                ctx.SaveChanges();

                return View("Index");
            }

            //this.LogRes.crearMenu(id);

            return View("../Shared/Error");


        }

        // GET: Cliente/Delete/5


        public ActionResult EditCliente(int id)
        {
            return View();
        }
        public ActionResult CompletarCliente()
        {

            return View();
        }

        [HttpGet]
        public ActionResult DetalleCliente(int id)
        {
            Cliente cliente = new Cliente();
            cliente = ctx.Cliente.Where(x => x.IdUsuario == id).FirstOrDefault();

            return View(cliente);
        }

        [HttpPost]
        public ActionResult DetalleCliente(Cliente cl)
        {
            int idUsuario;
            Int32.TryParse(Session["usuarioId"].ToString(), out idUsuario);
            Cliente cliente = ctx.Cliente.Where(x => x.IdUsuario == cl.IdUsuario).FirstOrDefault();

            //1 es admin
            if (cl.IdUsuario == idUsuario || Session["usuarioTipo"].ToString() == "1")
            {
                if (ModelState.IsValid)
                {
                    if (cliente != null)
                    {
                        cliente.Nombre = cl.Nombre;
                        cliente.Apellido = cl.Apellido;

                        ctx.SaveChanges();
                    }
                }

                return View(cliente);
            }

            return RedirectToRoute("Home/Index");

        }

        public ActionResult Reserva(int idResto)
        {
            HorariosReservaViewModel horarioReserva = InicializaHorarioReserva(idResto);
            return View("ReservaHora", horarioReserva);

        }

        [HttpGet]
        public ActionResult ReservaHora(int idResto)
        {

            HorariosReservaViewModel horarioReserva = InicializaHorarioReserva(idResto);
            return View("ReservaHora", horarioReserva);
        }
        [HttpPost]
        public ActionResult ReservaHora(HorariosReservaViewModel horarioReserva)
        {

            CultureInfo enUS = new CultureInfo("en-US");
            HorariosReservaViewModel nuevoHorarioReserva = InicializaHorarioReserva(horarioReserva.RestoId);
            if (horarioReserva.comensales != 0)

            {
                //string fechaHoy = DateTime.Today.ToShortDateString();
                //String fechaHora = fechaHoy + " " + horarioReserva.hora + ":00";
                //DateTime fechaHoraReserva = DateTime.ParseExact(fechaHora, "dd/MM/yyyy HH:mm:ss", enUS, DateTimeStyles.None);
                string fechaHoy = DateTime.Today.ToShortDateString();
                String fechaHora = fechaHoy + " " + horarioReserva.hora + ":00";
                DateTime fechaHoraReserva = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, int.Parse(horarioReserva.hora.Split(':')[0]), 0, 0);
                //Comentado temporalmente por la hora
                if (fechaHoraReserva < DateTime.Now.AddHours(1))
                {
                    ModelState.AddModelError("Hora", "No puede reservar con menos de una hora de anticipación");
                    return View("ReservaHora", nuevoHorarioReserva);
                }
                if (fechaHoraReserva < DateTime.Now)
                {
                    ModelState.AddModelError("Hora", "No puede reservar en ese horario");
                    return View("ReservaHora", nuevoHorarioReserva);
                }
                if (restauranteServicio.VerificaDisponibilidad(horarioReserva.RestoId, fechaHoraReserva, horarioReserva.comensales))
                {
                    var reserva = new ReservaViewModel();
                    reserva.CantidadComensales = horarioReserva.comensales;
                    reserva.FechaHoraReserva = fechaHoraReserva;
                    reserva.RestauranteId = horarioReserva.RestoId;
                    reserva.restauranteNombre = restauranteServicio.GetById(horarioReserva.RestoId).NombreComercial;
                    //var resto = restauranteServicio.GetById(horarioReserva.RestoId);
                    //reserva.Restaurante = resto;
                    List<Plato> listaDePlatos = LogCliente.ListarPlatosDelRestaurante(horarioReserva.RestoId);
                    List<PlatoViewModel> listadoPlatos = new List<PlatoViewModel>();
                    //cantidad de platos
                    var cantidadMaxima = restauranteServicio.GetById(horarioReserva.RestoId).CantidadClientes;

                    List<int> cantidades = new List<int>();
                    var cantidad = 0;
                    for (cantidad = 0; cantidad <= cantidadMaxima; cantidad++)
                    {
                        cantidades.Add(cantidad);
                    }
                    foreach (Plato plato in listaDePlatos)
                    {
                        listadoPlatos.Add(plato.Map());
                    }
                    foreach (var platoVM in listadoPlatos)
                    {
                        platoVM.cantidadPlatos = cantidades;
                        platoVM.cantidad = 0;
                    }
                    reserva.platos = listadoPlatos;

                    return View("Reserva", reserva);
                }
                ModelState.AddModelError("Hora", "No hay disponibilidad en ese horario");
                return View("ReservaHora", nuevoHorarioReserva);

            }

            ModelState.AddModelError("Comensales", "Debe elegir cantidad de comensales");
            return View("ReservaHora", nuevoHorarioReserva);
        }


        [HttpPost]
        public ActionResult Reserva(ReservaViewModel reserva)
        {
            var platosElegidos = new List<PlatosElegidosViewModel>();
            var reservaRealizada = new Reserva();
            reserva.Total = 0;
            var i = 0;
            for (i = 0; i < reserva.PlatoId.Count(); i++)
            //foreach (var plato in reserva.platos)
            {
                //if (plato.cantidad != null && plato.cantidad != 0)
                if (reserva.PlatoCantidad[i] > 0)
                {
                    var platoElegido = new PlatosElegidosViewModel();
                    Plato plato = logicaPlato.GetById(reserva.PlatoId[i]);
                    platoElegido.PlatoId = reserva.PlatoId[i];
                    platoElegido.Cantidad = reserva.PlatoCantidad[i];
                    platoElegido.nombrePlato = plato.NombrePlato;
                    platoElegido.subTotal = platoElegido.Cantidad * Convert.ToDouble(plato.Precio);
                    platosElegidos.Add(platoElegido);
                    reserva.Total = reserva.Total + Convert.ToDecimal(platoElegido.subTotal);
                    //reserva.PlatosElegidos.Add(platoElegido.Map());
                }
            }
            if (platosElegidos.Count() > 0)
            {
                reserva.platosElegidosVm = platosElegidos;
                ModelState.AddModelError("Platos", "No eligió ningún plato");

            }
            reserva.restauranteNombre = restauranteServicio.GetById(reserva.RestauranteId).NombreComercial;
            List<Plato> listaDePlatos = LogCliente.ListarPlatosDelRestaurante(reserva.RestauranteId);
            var cantidadMaxima = restauranteServicio.GetById(reserva.RestauranteId).CantidadClientes;
            List<PlatoViewModel> listadoPlatos = new List<PlatoViewModel>();
            foreach (Plato plato in listaDePlatos)
            {
                listadoPlatos.Add(plato.Map());
            }
            List<int> cantidades = new List<int>();

            var cantidad = 0;
            for (cantidad = 0; cantidad <= cantidadMaxima; cantidad++)
            {
                cantidades.Add(cantidad);
            }
            foreach (var platoVM in listadoPlatos)
            {
                platoVM.cantidadPlatos = cantidades;
                platoVM.cantidad = 0;
            }

            reserva.platos = listadoPlatos;
            return View("ConfirmaReserva", reserva);
        }

        /* Lista de platos del restaurante elegido*/
        public ActionResult ListaPlatos(int idResto)
        {
            var resto = new RestauranteViewModel();
            resto = restauranteServicio.GetById(idResto).Map();
            List<Plato> listaDePlatos = LogCliente.ListarPlatosDelRestaurante(idResto);

ReservAntes/Controllers/ReservaController.cs
using ReservAntes.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ReservAntes.Controllers
{
    public class ReservaController : Controller
    {

        dbReservantesEntities ctx = new dbReservantesEntities();

        ReservAntes.Models.LogicaReserva LogRes = new LogicaReserva();

        // GET: Reserva
        public ActionResult ReporteReservas()
        {
            var IdUsuario = this.Session["usuarioId"];
            int numID = Convert.ToInt32(IdUsuario);

            List<Reserva> MisReservasResto = LogRes.GetByUsuarioId(numID);

            return View(MisReservasResto);
        }

        [HttpPost]
        public ActionResult ReporteReservas(FormCollection form)
        {
            var IdUsuario = this.Session["usuarioId"];
            int numID = Convert.ToInt32(IdUsuario);

            //var fechaFil = form["FFiltro"];
            //Convert.ToDateTime(fechaFil);
            DateTime fechaFil = Convert.ToDateTime(form["FFiltro"]);

            List<Reserva> reservaFiltro = LogRes.FiltroReservas(numID, fechaFil);

            
            return View(reservaFiltro);
        }


  
        public ActionResult ReservaHorarios()
        {
            return View();
        }


        // GET: Reserva/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Reserva/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Reserva/Edit/5
        public ActionResult CancelarReserva(int id)
        {
            return View();
        }

        // POST: Reserva/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Reserva/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Reserva/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ReservAntes/Views/Cliente/ConfirmaReserva.cshtml
@using ReservAntes.ViewModels
@model  ReservaViewModel
@{
    Layout = "~/Views/Shared/_LayoutCliente.cshtml";
    ViewBag.Title = "ConfirmaReserva";
    int indexPlatos = 0;

}


<h2 class="thumbnail">Confirmar Reserva @Model.restauranteNombre</h2>
@using (Html.BeginForm("ConfirmarReserva", "Cliente", FormMethod.Post, new { reservaFinal = @Model }))
{
    @Html.HiddenFor(u => u.RestauranteId)
    @Html.HiddenFor(u => u.FechaHoraReserva)
    @Html.HiddenFor(u => u.CantidadComensales)
    @Html.HiddenFor(u => u.Total)

    <table class="table table-striped table-hover">
        <thead class="table table-bordered">
            <tr>
                <th>Plato</th>
                <th>Cantidad</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody class="table table-hover">

            @foreach (var item in Model.platosElegidosVm)
            {

                <tr class="active">
                    <td>
                        @Html.DisplayFor(modelItem => item.nombrePlato)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Cantidad)
                        @*@Html.HiddenFor(u => u.PlatoElegidoCantidad[indexPlatos])*@
                        <input type="hidden" value="@item.Cantidad" name="PlatoElegidoCantidad[@indexPlatos]" />
                        <input type="hidden" value="@item.PlatoId" name="PlatoElegidoId[@indexPlatos]" />
                        @Html.HiddenFor(m => item.PlatoId)
                    </td>

                    <td>
                        $ @Html.DisplayFor(modelItem => item.subTotal)
                    </td>
                </tr>
                indexPlatos++;
            }

        </tbody>

    </table>

    @*<button type="submit" class="btn btn-primary">Reservar</button>*@
    <div class="container-fluid">
        <div class="thumbnail" style="width:500px;"> Cantidad de Comensales: <b>@Html.DisplayFor(model => model.CantidadComensales)</b></div>

        <div class="thumbnail" style="width:500px;">
            Horario: @Html.DisplayFor(model => model.FechaHoraReserva.Hour) :00 horas 
        </div>

        <div class="thumbnail" style="width:500px;">
            <h3>Total: $ @Html.DisplayFor(model => model.Total)  </h3>
        </div>

    </div>
        <button type="submit" class="btn btn-default btn-success btn-lg btn-block">Confirmar Reserva</button>

        }
        @*<h4>Su código de reserva es @Model.CodigoReserva</h4>
        <button onclick="location.href='@Url.Action("Index", "Cliente")';return false;" class="btn btn-success">Volver al Inicio</button>*@

ReservAntes/Views/Cliente/DetalleCliente.cshtml
@model ReservAntes.Cliente
@{
    ViewBag.Title = "CompletarCliente";
    Layout = "~/Views/Shared/_LayoutCliente.cshtml";
}

<div>
    <div class="jumbotron">
        <div class="table-responsive">
            <table class="table table-bordered table-condensed table-striped">
                <thead>
                    <tr>
                        <th>
                            Usuario
                        </th>
                        <th>
                            Nombre
                        </th>
                        <th>
                            Apellido
                        </th>
                        <th>
                            Email
                        </th>
                    </tr>
                </thead>

                <tbody>
                    <tr>
                        <td>
                            @Model.Usuario.Username
                        </td>
                        <td>
                            @Model.Nombre
                        </td>
                        <td>
                            @Model.Apellido
                        </td>
                        <td>
                            @Model.Usuario.Email
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        
    </div>

    <h4 class="breadcrumb">Complete y/o edite sus datos:</h4>
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-6">

                @using (Html.BeginForm("DetalleCliente", "Cliente"))
            {
                    @Html.Hidden("IdUsuario", Model.IdUsuario)

                    <div class="form-group">
                        <label>Nombres :</label>
                        @Html.TextBoxFor(Model => Model.Nombre, new { @class = "form-control" })
                        @Html.ValidationMessageFor(Model => Model.Nombre, "", new { @class = "text-danger" })


                    </div>
                    <div class="form-group">
                        <label>Apellido:</label>
                        @Html.TextBoxFor(Model => Model.Apellido, new { @class = "form-control" })
                        @Html.ValidationMessageFor(Model => Model.Apellido, "", new { @class = "text-danger" })


                    </div>
                    @*<div class="form-group">
                        <label>Domicilio:</label>
                        @Html.TextBoxFor(Model => Model.Domicilio, new { @class = "form-control" })
                    </div>*@


                    <button type="submit" class="btn btn-primary">Cambiar</button>
                }
            </div>
        </div>
    </div>


</div>

ReservAntes/Views/Cliente/Index.cshtml
@using ReservAntes.ViewModels
@model List<RestauranteViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutCliente.cshtml";
}


<h4 class="breadcrumb">Restaurantes disponibles cerca tuyo</h4>

ReservAntes/Views/Cliente/ListaPlatos.cshtml
@model  Restaurante
@{
    ViewBag.Title = "Platos";
    //ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutCliente.cshtml";
}

<div class="jumbotron">
    <h2>@Model.NombreComercial</h2>
    @Model.Domicilio <p></p>
</div>
<h4 class="thumbnail text-center">Menú</h4>
<div class=" thumbnail">
    @*@using (Html.BeginForm("Reservar", "Cliente", new (idResto =)
        {*@
    @Html.HiddenFor(u => u.IdRestaurante)

    <table class="table table-hover">
        <thead class="table-bordered">
            <tr>
                <td>Plato</td>
                <td>Precio</td>
            </tr>

        <thead />
        <tbody class="table-hover">
            @foreach (var plato in Model.Plato)
            {
                <tr class="table-bordered">
                    <td>@plato.NombrePlato</td>
                    <td>$@plato.Precio</td>
                </tr>
            }


        </tbody>
    </table>

    @*@2 es cliente *@
    @if (Session["usuarioTipo"] != null && Session["usuarioTipo"].ToString() == "2")
    {
        @Html.ActionLink("Reservar", "ReservaHora", "Cliente", new { idResto = Model.IdRestaurante }, new { @class = "btn btn-default btn-success btn-lg btn-block" })
    }

    @*<button type="submit" class="btn btn-primary">Reservar</button>*@
    @*<button onclick="location.href='@Url.Action("Index", "Cliente")';return false;" class="btn btn-danger">Cancelar</button>*@

    </div>

ReservAntes/Views/Cliente/PagarReserva.cshtml
@{
    ViewBag.Title = "PagarReserva";
    Layout = "~/Views/Shared/_LayoutCliente.cshtml";
}

<h2>Pagar Reserva</h2>
@ViewBag.LinkMP

<a href="@ViewBag.LinkMP" class="btn btn-default">Pagar</a>

@ViewBag.LinkMP

ReservAntes/Views/Cliente/Reserva.cshtml
@using ReservAntes.ViewModels
@model  ReservaViewModel
@{
    ViewBag.Title = "Reservar";
    Layout = "~/Views/Shared/_LayoutCliente.cshtml";
    int indexPlatos = 0;

}

<h2 class="thumbnail text-center">Reservar en <b>@Model.restauranteNombre</b></h2>


@if (Model.platosElegidosVm==null)
{
    using (Html.BeginForm("Reserva", "Cliente", FormMethod.Post, new { reserva = @Model }))
    {
        @Html.HiddenFor(u => u.RestauranteId)
        @Html.HiddenFor(u => u.FechaHoraReserva)
        @Html.HiddenFor(u => u.CantidadComensales)
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })

        <div class="table-responsive thumbnail">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <td>Nombre</td>
                        <td>Precio</td>
                        <td>Cantidad</td>
                    </tr>

                <thead />
                <tbody>

                    @foreach (var plato in Model.platos)
                    {
                        <tr>
                            <td>@plato.NombrePlato</td>
                            <td>$@plato.Precio</td>
                            <td>
                                @Html.DropDownListFor(u => u.PlatoCantidad[indexPlatos], new SelectList(plato.cantidadPlatos), "Cantidad", new { @class = "form-control" })
                                <input type="hidden" value="@plato.Id" name="PlatoId[@indexPlatos]" />
                                @Html.HiddenFor(m => plato.Id)
                            </td>
                        </tr>
                        indexPlatos++;
                    }

                </tbody>
            </table>
        </div>
        <br />

        @*@Html.ActionLink("Reservar", "PlatosElegidos", "Cliente", new { @reserva = @Model }, new { @class = "btn btn-default btn-success btn-lg btn-block" })*@
        <div class="jumbotron"><button type="submit" class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-ok-sign"></span>  Seleccionar platos</button></div>

            }
}
@*@if (Model != null && Model.platosElegidosVm != null && Model.platosElegidosVm.Count > 0)

{
   
}*@



@*<a href="<% Response.Write(preference[" response"]["init_point"]); %>">Pagar</a>*@

ReservAntes/Views/Cliente/ReservaCliente.cshtml
@using System.Globalization
@model List<Reserva>
@{
    Layout = "~/Views/Shared/_LayoutCliente.cshtml";

    ViewBag.Title = "ReservaCliente";
}
<div class="thumbnail">
    <h2 class="text-center">Mis reservas</h2><br />


    <div class="table-responsive">
        <table class="table-bordered table-striped table-condensed" style="width: 100%;">
            <thead>
                <tr>
                    <th>Restaurante</th>
                    <th>Fecha y hora</th>
                    <th>Código</th>
                    <th>Comensales</th>
                    <th>Estado de la Reserva</th>
                    <th>Pago</th>

                </tr>
            </thead>

            <tbody>
                @foreach (Reserva reserva in Model)
                {
                <tr>
                    <td>
                        @reserva.Restaurante.NombreComercial
                    </td>
                    <td>
                        @reserva.FechaHoraReserva.ToLongDateString() a las @reserva.FechaHoraReserva.ToShortTimeString()
                    </td>
                    <td>
                        <h3><b>  @reserva.CodigoReserva</b></h3>
                    </td>
                    <td>
                        @reserva.CantidadComensales
                    </td>
                    <td>
                        @reserva.EstadoReserva.Descripcion
                    </td>
                    <td>
                        @{
                            if (reserva.EstadoReserva.Descripcion == "Reservado" || reserva.EstadoReserva.Descripcion == "Aceptado")
                            {
                                @Html.ActionLink("Efectivo", "PagarEnEfectivo", "Cliente", new { idReserva = reserva.Id }, new { @class = "btn btn-default" })
                                <a href="@reserva.LinkMP" class="btn btn-default">Mercado Pago</a>
                            }
                        }
                        
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>

ReservAntes/Views/Cliente/ReservaHora.cshtml
@using ReservAntes.ViewModels
@model  HorariosReservaViewModel
@{
    /**/

    ViewBag.Title = "ReservaHora";
    Layout = "~/Views/Shared/_LayoutCliente.cshtml";
}

<p></p>
<p></p>
<br />
<div class="thumbnail">
    <div class="row">
        <div class="col-lg-5"></div>

        <h2 class="text-center">Verifica si hay disponibilidad</h2>
        @using (Html.BeginForm("ReservaHora", "Cliente", FormMethod.Post))
        {
            @Html.HiddenFor(u => u.RestoId)
            <div class="col-lg-2"></div>
            <div class="col-lg-4">

                <div class="form-group">
                    <label>Hora:</label>
                    @Html.DropDownListFor(u => u.hora, new SelectList(Model.Horarios), "Hora", new { @class = "form-control" })
                    @Html.ValidationMessageFor(u => u.hora, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label>Cantidad de Personas:</label>
                @Html.DropDownListFor(u => u.comensales, new SelectList(Model.cantidadMaxima), "Cantidad de Comensales", new { @class = "form-control" })
                @Html.ValidationMessageFor(u => u.comensales, "", new { @class = "text-danger" })
            </div><br />
            <div class="col-lg-5"></div>

            <button type="submit" class="btn btn-primary btn-lg">Reservar</button>
            @Html.ValidationSummary(true, "")

        }
    </div>
</div>